//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Litium.Synchronization.Export.L5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Litium.Synchronization.Export.L5.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order could not be exported. Order id {0}.
        /// </summary>
        internal static string ExportingOrderError {
            get {
                return ResourceManager.GetString("ExportingOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization could not be exported. Customer number {0}.
        /// </summary>
        internal static string ExportingOrganizationError {
            get {
                return ResourceManager.GetString("ExportingOrganizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person could not be exported. Customer number {0}.
        /// </summary>
        internal static string ExportingPersonError {
            get {
                return ResourceManager.GetString("ExportingPersonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is missing: {0}.
        /// </summary>
        internal static string OrderIsMissing {
            get {
                return ResourceManager.GetString("OrderIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping of order not succedded: {0}.
        /// </summary>
        internal static string OrderMappingError {
            get {
                return ResourceManager.GetString("OrderMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is missing: {0}.
        /// </summary>
        internal static string OrganizationIsMissing {
            get {
                return ResourceManager.GetString("OrganizationIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping of organization not succedded: {0}.
        /// </summary>
        internal static string OrganizationMappingError {
            get {
                return ResourceManager.GetString("OrganizationMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is missing: {0}.
        /// </summary>
        internal static string PersonIsMissing {
            get {
                return ResourceManager.GetString("PersonIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping of person not succedded: {0}.
        /// </summary>
        internal static string PersonMappingError {
            get {
                return ResourceManager.GetString("PersonMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file: {0}.
        /// </summary>
        internal static string WritingFile {
            get {
                return ResourceManager.GetString("WritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be written. File name {0}. Exception message {1}.
        /// </summary>
        internal static string WritingFileError {
            get {
                return ResourceManager.GetString("WritingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is missing.
        /// </summary>
        internal static string WritingFileErrorNoFileName {
            get {
                return ResourceManager.GetString("WritingFileErrorNoFileName", resourceCulture);
            }
        }
    }
}
