using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Text;

namespace Litium.Synchronization.Abstraction.Sales
{
    [Serializable]
    public class OrderRow : BaseItem
    {
        public string ArticleNumber { get; set; }
        public string AutoMergeKey { get; set; }
        public Guid CampaignSystemId { get; set; }
        public string Comments { get; set; }
        public Guid DeliverySystemId { get; set; }
        public decimal DiscountAmount { get; set; }
        public string DiscountDescription { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string ExternalCampaignId { get; set; }
        public string ExternalOrderRowId { get; set; }
        public bool IsAutoGenerated { get; set; }
        public Guid OrderSystemId { get; set; }
        public string OrderRowDescription { get; set; }
        public short OrderRowStatus { get; set; }
        public Guid ProductSystemId { get; set; }
        public decimal Quantity { get; set; }
        public Guid? RmaRowSystemId { get; set; }
        public Guid? SalesOrderRowSystemId { get; set; }
        public string SKUCode { get; set; }
        public Guid SystemId { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalPriceWithVAT { get; set; }
        public decimal TotalVATAmount { get; set; }
        public decimal UnitCampaignPrice { get; set; }
        public decimal UnitListPrice { get; set; }
        public decimal VATPercentage { get; set; }

    }
}
