//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Litium.Synchronization.Import {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Litium.Synchronization.Import.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization of the file not succedded: {0}.
        /// </summary>
        internal static string DeserializationError {
            get {
                return ResourceManager.GetString("DeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing item: {0}.
        /// </summary>
        internal static string DisposeException {
            get {
                return ResourceManager.GetString("DisposeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field template is missing: {0}.
        /// </summary>
        internal static string FieldTemplateMissing {
            get {
                return ResourceManager.GetString("FieldTemplateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File processed succeeded, deleting file..
        /// </summary>
        internal static string FileCompletedSucceeded {
            get {
                return ResourceManager.GetString("FileCompletedSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file: {0}.
        /// </summary>
        internal static string FileProcessing {
            get {
                return ResourceManager.GetString("FileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t import the order: {0}.
        /// </summary>
        internal static string ImportingOrderError {
            get {
                return ResourceManager.GetString("ImportingOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving file to &apos;{0}&apos;..
        /// </summary>
        internal static string MovingFile {
            get {
                return ResourceManager.GetString("MovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move file to &apos;{0}&apos;-folder, exception: {1}.
        /// </summary>
        internal static string MovingFileError {
            get {
                return ResourceManager.GetString("MovingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order mapping not succeeded: {0}.
        /// </summary>
        internal static string OrderMappingError {
            get {
                return ResourceManager.GetString("OrderMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create or update order: {0}.
        /// </summary>
        internal static string OrderUpdateCreateError {
            get {
                return ResourceManager.GetString("OrderUpdateCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization mapping not succeeded: {0}.
        /// </summary>
        internal static string OrganizationMappingError {
            get {
                return ResourceManager.GetString("OrganizationMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person mapping not succeeded: {0}.
        /// </summary>
        internal static string PersonMappingError {
            get {
                return ResourceManager.GetString("PersonMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read file &apos;{0}&apos;, exception: {1}.
        /// </summary>
        internal static string ReadingFileError {
            get {
                return ResourceManager.GetString("ReadingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete folder &apos;{0}&apos;, exception: {1}.
        /// </summary>
        internal static string RemoveDirectoryError {
            get {
                return ResourceManager.GetString("RemoveDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete file &apos;{0}&apos;, exception: {1}.
        /// </summary>
        internal static string RemoveFileError {
            get {
                return ResourceManager.GetString("RemoveFileError", resourceCulture);
            }
        }
    }
}
